### ISSUE TITLE
Image of team member 'B. juarez' is not displaying in 'Pio FC' team page

### ISSUE THREAD

**Issue by lucaspiritogit** [midudev/kings-league-project#125]
# Reproducing the problem
If we go inside the team profile route:
https://kingsleague.dev/team/pio-fc/

We can see that the image of **B. Juarez** is not displaying correctly
![image](https://user-images.githubusercontent.com/81486152/211125150-b55a5d2e-045e-491d-990f-c322e13bb978.png)

And if we call the API with the players name:

https://api.kingsleague.dev/static/players/pio-fc-b-ju%C3%A1rez.png

We get a JSON response saying: 
```json
{"message":"Not Found"}
```
# Details
_Doing a normal refresh or CTRL+SHIFT+R refresh to ensure that the cache is clean does not bring the image neither._

If more information is needed or my contribution is lacking in some way, im happy to revisit this issue.
Thank you!

**Comment by Felix-Icaza** [comment]
Adding more images that not load correctly.

**Team URL**: [https://kingsleague.dev/team/los-troncos-fc/](https://kingsleague.dev/team/los-troncos-fc/)

![Screenshot_2023-01-07_08-35-32](https://user-images.githubusercontent.com/38303370/211156231-8456d20c-1676-4806-a78c-6788758ac4ac.png)

**Team URL**: [https://kingsleague.dev/team/saiyans-fc/](https://kingsleague.dev/team/saiyans-fc/)

![Screenshot_2023-01-07_08-36-10](https://user-images.githubusercontent.com/38303370/211156287-49b69ae2-3489-451a-af3e-a74a45273bb7.png)

**Team URL**: [https://kingsleague.dev/team/aniquiladores-fc/](https://kingsleague.dev/team/aniquiladores-fc/)

![Screenshot_2023-01-07_08-36-39](https://user-images.githubusercontent.com/38303370/211156318-17508b4b-a709-48d7-9489-0587edf80ebb.png)

**Comment by Fasping** [comment]
[string.sanitize()](https://gomakethings.com/how-to-sanitize-html-strings-with-vanilla-js-to-reduce-your-risk-of-xss-attacks/)

**Comment by magdaniele** [comment]
This issue was already fixed, try to see the page again
