### ISSUE TITLE
Broken responsive on small devices

### ISSUE THREAD

**Issue by TheLokin** [midudev/kings-league-project#198]
# [Home](https://kingsleague.dev)
![responsive](https://user-images.githubusercontent.com/41437556/211170420-8c3d09ec-b69e-4f33-bcfc-5b86e5af028e.PNG)

# [Calendario](https://kingsleague.dev/calendario)
![calendario](https://user-images.githubusercontent.com/41437556/211170467-0b0e7487-fcf1-4bd0-8b5f-6708cd34fb5c.PNG)

# [Contacto](https://kingsleague.dev/contacto)
![contacto](https://user-images.githubusercontent.com/41437556/211170522-d53c67cc-4dd7-4c9a-ae72-18e4b1b80916.PNG)

# [Equipo](https://kingsleague.dev/team/ultimate-mostoles)
![equipo](https://user-images.githubusercontent.com/41437556/211170638-7dc100d2-6c1a-41fa-b596-558e0e78ca98.PNG)

**Comment by GenaroIBC** [comment]
Contact page responsive fixed in #200

**Comment by PChaparro** [comment]
`/` and `/contacto` pages fixed in #236.
