### ISSUE TITLE
Safari iPhone 12 bit

### ISSUE THREAD

**Issue by usarral** [midudev/kings-league-project#210]
Safari UI is broken on iPhone![image](https://user-images.githubusercontent.com/41452910/211174343-00eb4d63-38c2-412e-9a44-b63bf5e84722.png)![image](https://user-images.githubusercontent.com/41452910/211174342-9246cc73-0011-49e2-8d42-77cf2312a249.png) ![image](https://user-images.githubusercontent.com/41452910/211174346-1c301c9f-7623-4c6e-84eb-b82bcca08b45.png)![image](https://user-images.githubusercontent.com/41452910/211174349-052b2683-88cb-4eff-a478-04f3dcc53c01.png)

**Comment by Fasping** [comment]
sorry you can specify more details about what iphone model is?
and what browsers ? 

thank you
