### ISSUE TITLE
Jijantes-fc and xbuyer-team broken link

### ISSUE THREAD

**Issue by PChaparro** [midudev/kings-league-project#240]
Jijantes-fc link is broken on the schedules tables: 

<table><tr><td>
    <p>Home page:</p>
    <img src="https://user-images.githubusercontent.com/94259578/211198141-dbf60104-e7e6-4ccc-a057-357592e4c24c.png" height="440px"/>
</td><td>
    <p>/Calendario page:</p>
    <img src="https://user-images.githubusercontent.com/94259578/211198149-f8bfbe79-dd78-44d7-a465-28536c602fcd.png" height="440px"/>
</td></tr></table>

Probably the reason is the mapping done in the schedule scraper, but the problem is that the logo is named 'jijantes.svg', so, if we change the team name to 'jijantes-fc', the image will broke.

**Comment by magdaniele** [comment]
That's because in the api we are taking the short names or something like that instead the complete name
![image_2023-01-08_093226693](https://user-images.githubusercontent.com/25647270/211201972-f60fea4f-9cc3-4ae7-915a-2788eaa7c328.png)
Its the same problem to xbuyers and el-barrio teams

**Comment by PChaparro** [comment]
> That's because in the api we are taking the short names or something like that instead the complete name 

@magdaniele That's true. "el-barrio" team is working, but "xbuyer-team" isn't. The problem is that we can't change / remove than mapping directly because the logos will broke.

**Comment by magdaniele** [comment]
@PChaparro we have another problem, I was trying to fix this issue but I realize that some scrapping functions are not working

**Comment by PChaparro** [comment]
> @PChaparro we have another problem, I was trying to fix this issue but I realize that some scrapping functions are not working

@magdaniele The scrapers are working well for me, maybe you need to re-install the pnpm packages. I just added a solution from the front-end service file. Maybe this can be also fixed directly from the scraper, that would be an amazing fix.

**Comment by magdaniele** [comment]
@PChaparro I'm using npm actually, but I think that that can't be a problem because I believe that npm and pnpm are almost the same, no?

**Comment by magdaniele** [comment]
> > @PChaparro we have another problem, I was trying to fix this issue but I realize that some scrapping functions are not working
> 
> @magdaniele The scrapers are working well for me, maybe you need to re-install the pnpm packages. I just added a solution from the front-end service file. Maybe this can be also fixed directly from the scraper, that would be an amazing fix.

I like your solution, is pretty optimal I think. But I usually prefer not modify the front, in my opinion make changes in the back is better and that could be fixed in less code lines only modifying the scrapper but It's only my thinking xD

**Comment by PChaparro** [comment]
> @PChaparro I'm using npm actually, but I think that that can't be a problem because I believe that npm and pnpm are almost the same, no?

I just tried with npm instead of pnpm and the scrapers still works, maybe the problem is the node version? I'm using node v19.3.0. It should be nice to know if others users have the same problem.
