### ISSUE TITLE
Some scrappers are broken

### ISSUE THREAD

**Issue by magdaniele** [midudev/kings-league-project#249]
I was trying to figure out what was happening with the issue: https://github.com/midudev/kings-league-project/issues/240  and I realized that some scrappers are not working. I don't know if that only happen to me

![image_2023-01-08_095322710](https://user-images.githubusercontent.com/25647270/211203033-4437cf2b-54db-4a8e-9a71-eadc0ec129ba.png)

**Comment by midudev** [comment]
You need to use Node 18.
