### ISSUE TITLE
schedule table (home/schedule page)

### ISSUE THREAD

**Issue by nightmir3** [midudev/kings-league-project#254]
# mobile
![mobile-before](https://user-images.githubusercontent.com/40222833/211206018-a678853b-b15b-4068-ade2-6b4fc41c9779.png)

# tablet
![ipad-home-before](https://user-images.githubusercontent.com/40222833/211206013-3def5b28-97c0-419b-af0d-608b0f62ed6b.png)
---
![ipad-before](https://user-images.githubusercontent.com/40222833/211206017-171c043e-32c1-47ba-bc8f-e75d3428f7b8.png)

# laptop <1500 resolution
![laptop-home-1500-before](https://user-images.githubusercontent.com/40222833/211206015-ba31aec6-5248-41a0-b9a4-cb39326a567b.png)
---
![laptop-1500-before](https://user-images.githubusercontent.com/40222833/211206016-fd75baf1-fcec-47f3-89a9-9b19aa0378ea.png)

**Comment by PChaparro** [comment]
It isn't fixed on #236?

**Comment by nightmir3** [comment]
1. second team logo and text should be inverted on screens from tablet to laptop, mobile works
2. padding in center colunm (time/vs/score) should be the same
3. mobile screens reduce the padding in center colunm

**Comment by PChaparro** [comment]
@nightmir3 2 and 3 items fixed in #276, the first one was fixed by other user.

**Comment by nightmir3** [comment]
ok, closed
