### ISSUE TITLE
Vínculo incorrecto en tabla de jornadas

### ISSUE THREAD

**Issue by sebaxp** [midudev/kings-league-project#259]
Vínculos incorrectos del nombre corto en la tarjeta de las jornadas:

JFC  Cambiar de https://kingsleague.dev/team/jijantes a https://kingsleague.dev/team/jijantes-fc/
PIO Cambia de https://kingsleague.dev/team/pio a https://kingsleague.dev/team/pio-fc/
TFC Cambiar de https://kingsleague.dev/team/los-troncos a https://kingsleague.dev/team/los-troncos-fc/

![image](https://user-images.githubusercontent.com/14959227/211208922-92f818ac-6c5c-4c56-9c79-effc0da6734c.png)

**Comment by PChaparro** [comment]
@sebaxp esto se arregló en #252. Incluso en [producción](https://kingsleague.dev/) ya está arreglado.
