### ISSUE TITLE
Error Cannot destructure property 'mvp' of '(intermediate value)' as it is null.

### ISSUE THREAD

**Issue by Ameth** [midudev/kings-league-project#297]
En la linea 34 sale el error que dice kings-league-project\src\pages\index.astro:34:11

![imagen](https://user-images.githubusercontent.com/1568292/211641321-a7bb7b57-31e5-441d-827e-f8a08e433ae9.png)

**Comment by Felix-Icaza** [comment]
Tienes que ejecutar el comando `pnpm dev:api` o si estás usando npm `npm run dev:api`, luego tendrás que iniciar sesión en cloudflare y por último tienes que habilitar el modo local pesionando la tecla `[l]`. Esto es necesario para poder levantar la API en desarrollo.
