### ISSUE TITLE
broken resposive mobile 

### ISSUE THREAD

**Issue by JordiNodeJS** [midudev/kings-league-project#299]
in devtools when push mobil button to see the web how it shows up then it happens this 👇
![issue](https://user-images.githubusercontent.com/71975008/211644997-b23c80bb-8edf-4cbe-b5d6-3caa6ad99318.png)

**Comment by PChaparro** [comment]
This was fixed on #200. Check that you are using the last version of the repository and close this issue if all is OK: 

![image](https://user-images.githubusercontent.com/94259578/211673518-f5fa45f8-1410-4d82-b9c0-6bf2db8dd07c.png)

**Comment by JordiNodeJS** [comment]
yep, you`re right 👌
