### ISSUE TITLE
 the https://api.kingsleague.dev/players-12 endpoint is not returning name, lastName, firstName

### ISSUE THREAD

**Issue by KewinBarboza** [midudev/kings-league-project#318]
![image](https://user-images.githubusercontent.com/32785129/212173986-846b6385-e35a-429c-98ce-e036da728f4e.png)

**Comment by PChaparro** [comment]
@KewinBarboza thanks for reporting this issue. I've already made a pull request to fix this, if the pull request is accepted, this issue will close automatically.
